### ISSUE TITLE
Uncaught PHP Exception Exception: "Unknown method findPublishedRegularWithoutGuestsByIds"

### ISSUE THREAD

**Issue by ReneLuecking** [madeyourday/contao-rocksolid-mega-menu#10]
Inside the class `MenuCustom` the method `PageModel::findPublishedRegularWithoutGuestsByIds` get's called. This method does not exist anymore.

https://github.com/madeyourday/contao-rocksolid-mega-menu/blob/e6b31b41a34236bbeea1120c00281227aafb1a9f/src/Module/MenuCustom.php#L37

**Comment by ausi** [comment]
Fixed in version 2.2.4
