### ISSUE TITLE
PHP 7 Warning rsmm_default.html5

### ISSUE THREAD

**Issue by zonky2** [madeyourday/contao-rocksolid-mega-menu#4]
`Warning: count(): Parameter must be an array or an object that implements Countable`

#116 https://github.com/madeyourday/contao-rocksolid-mega-menu/blob/9b633879b01833dba8c0d4c23a6ea3cb1cebf362/src/Resources/contao/templates/rsmm_default.html5#L116

may be, you can cast as array

```
<?php if (count((array) $column['pages'])): ?>
```

**Comment by ausi** [comment]
We should probably replace the line https://github.com/madeyourday/contao-rocksolid-mega-menu/blob/9b633879b01833dba8c0d4c23a6ea3cb1cebf362/src/Module/Menu.php#L132 with

```php
$column['pages'] = array();
```

**Comment by zonky2** [comment]
```
$column['pages'] = [];
```
;-)
