### ISSUE TITLE
alt-Tag wird mit den Metadaten aus Titel befüllt

### ISSUE THREAD

**Issue by netzarbeiter** [madeyourday/contao-rocksolid-mega-menu#5]
Wenn man ein Mega Menu mit einem «mega-dropdown-image» erstellt, werden die Daten für das alt-Tag aus dem Metadaten-Feld «Titel» bezogen. Ich hätte erwartet, dass für die Angaben das Metadaten-Feld «Alt» verwendet wird.

**Comment by ausi** [comment]
Sollte im master-Branch behoben sein. 
Kannst du bitte testen ob  
`"madeyourday/contao-rocksolid-mega-menu": "dev-master as 2.1.99",`  
bei dir funktioniert?

**Comment by netzarbeiter** [comment]
Funktioniert bei mir jetzt einwandfrei, vielen Dank.

**Comment by ausi** [comment]
Ist jetzt released als Version 2.1.1
