### ISSUE TITLE
Keine Child-Level > 1 im Markup beim Typ "Navigation"

### ISSUE THREAD

**Issue by k-webdesign** [madeyourday/contao-rocksolid-mega-menu#6]
Hi, ich habe festgestellt, dass beim Auswählen des Typs "Navigation" in einer MegaMenü-Spalte zwar die Referenzseite und das Stop-Level gewählt werden kann, jedoch werden die Child-Level tiefer als 1 darunter dann nicht ausgegeben. Ich wähle z.B. den Menüpunkt "Nachhaltigkeit" aus und mir werden zwar die direkten Kind-Elemente angezeigt, aber nicht das dritte Level. Das geht nur, wenn ich ein Modul einfüge, bei dem ich eine Referenzseite setze und das ist ziemlich umständlich.

So sollte es aussehen (das erreichen wir, indem der Typ auf "eigener HTML-Code" steht und ein Modul included wird)
<img width="696" alt="Bildschirmfoto 2022-03-09 um 17 43 22" src="https://user-images.githubusercontent.com/4130440/157489573-7435ecfa-f7e2-4321-8c2f-1a3681526bb0.png">

Die Seitenstruktur:
<img width="387" alt="Bildschirmfoto 2022-03-09 um 17 43 56" src="https://user-images.githubusercontent.com/4130440/157489752-a86f1084-d2be-48e8-8438-be151da13673.png">

Wenn der Typ auf "Navigation" steht und die Referenzseite "Nachhaltigkeit" auswählt wird:
<img width="395" alt="Bildschirmfoto 2022-03-09 um 17 45 14" src="https://user-images.githubusercontent.com/4130440/157489894-60fee034-fdef-4489-8c2d-4bc168854596.png">

... erhalte ich im Quellcode das:
<img width="778" alt="Bildschirmfoto 2022-03-09 um 17 45 56" src="https://user-images.githubusercontent.com/4130440/157489938-b07e6591-74c5-4728-ab5f-52bc8b92fd93.png">

Und im Frontend folglich das:
<img width="524" alt="Bildschirmfoto 2022-03-09 um 17 46 03" src="https://user-images.githubusercontent.com/4130440/157489976-c5a64a4a-4569-4ee5-b3d1-42c546a64a13.png">

**Comment by ausi** [comment]
Ich konnte das Problem nicht reproduzieren. Wurde eventuell eines der Template *rsmmnav_default.html5* oder *rsmm_default.html5* überschrieben?

**Comment by ausi** [comment]
Kann dieses Issue geschlossen werden?
