### ISSUE TITLE
Undefined variable $arrPage when using Custom Mega Menu

### ISSUE THREAD

**Issue by Arachnos** [madeyourday/contao-rocksolid-mega-menu#7]
Hi everyone,

An error `Warning: Undefined variable $arrPage` appears when using the Custom Mega Menu.

The Symfony Profiler tells the error is on line 58 in file [vendor/madeyourday/contao-rocksolid-mega-menu/src/Module/MenuCustom.php](https://github.com/madeyourday/contao-rocksolid-mega-menu/blob/bfc912f1052b3162d1b59ed9889c0a0946b1f082/src/Module/MenuCustom.php) (see screenshot) : 
```
    while ($objPages->next()) {
            $_groups = \StringUtil::deserialize($arrPage['groups']);
            if (!$arrPage['protected'] || BE_USER_LOGGED_IN || (is_array($_groups) && count(array_intersect($_groups, $groups))) || $this->showProtected) {
                $arrPages[$objPages->id] = $this->getPageData($objPages);
                if ($objPages->rsmm_enabled) {
                    $arrPages[$objPages->id]['subitems'] = $this->renderNavigation($objPages->id);
                }
            }
        }
```

It seems there is a "s" missing : the variable is above named `$arrPages`.

![image](https://user-images.githubusercontent.com/820562/168180042-85801008-2178-43f0-b324-871f1938c595.png)

Thanks is advance for solving this issue !

Étienne

**Comment by ausi** [comment]
Fixed in version 2.2.4
