### ISSUE TITLE
Order changes in front end after update to 2.2

### ISSUE THREAD

**Issue by netzarbeiter** [madeyourday/contao-rocksolid-mega-menu#8]
**contao-rocksolid-mega-menu 2.1.4**

Site structure back end:
- Link 1.1 (ID 10)
- Link 1.2 (ID 5)
- Link 1.3 (ID 6)
- Link 1.4 (ID 2)
- Link 1.5 (ID 3)

front end output:
- Link 1.1 (ID 10)
- Link 1.2 (ID 5)
- Link 1.3 (ID 6)
- Link 1.4 (ID 2)
- Link 1.5 (ID 3)

**contao-rocksolid-mega-menu 2.2.0**

Site structure back end:
- Link 1.1 (ID 10)
- Link 1.2 (ID 5)
- Link 1.3 (ID 6)
- Link 1.4 (ID 2)
- Link 1.5 (ID 3)

front end output:
- Link 1.4 (ID 2)
- Link 1.5 (ID 3)
- Link 1.2 (ID 5)
- Link 1.3 (ID 6)
- Link 1.1 (ID 10)

I had to go back on version 2.1.4 to get the "correct" front end order back.

**Comment by ausi** [comment]
We probably need to create a migration for that similar to the one from Contao: https://github.com/contao/contao/blob/001cea17fe99c1d2a44206c57333f49dfb594bae/core-bundle/src/Migration/Version410/OrderFieldMigration.php

**Comment by netzarbeiter** [comment]
It doesn't work correctly. Still the same behaviour as in 2.2.0.

**Comment by ausi** [comment]
Please try again with version 2.2.2 ☺️

**Comment by netzarbeiter** [comment]
Now it works fine again. Thank you.
