### ISSUE TITLE
Uncaught PHP Exception ErrorException: "Warning: Undefined array key "groups" ( DebugMode On )

### ISSUE THREAD

**Issue by netSpeedyTV** [madeyourday/contao-rocksolid-mega-menu#9]
httpdocs/vendor/madeyourday/contao-rocksolid-mega-menu/src/Module/MenuCustom.php line 56
{
    "exception": {}
}

----------------------------------------
PHP 8.0.x

**Comment by netSpeedyTV** [comment]
Change line 56 in:

	$_groups = StringUtil::deserialize($arrPages->groups);

Fix it

**Comment by ausi** [comment]
Fixed in version 2.2.4
